# Site settings
title: Codility Solution
email: kamoljan@gmail.com
description: "Tasks are taken from [Codility.com](http://Codility.com)"
baseurl: ""
url: "http://kamoljan.github.io"
twitter_username: kamoljan
github_username:  kamoljan

# Build settings
markdown: kramdown
permalink: pretty
